exclude: |
  (?x)(

  )
default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: ruff
        name: Fix with Ruff
        language: system
        types: [python]
        entry: poetry run ruff

      - id: black
        name: Format with Black
        language: system
        types: [python]
        entry: poetry run black

      - id: mypy
        name: Type check with Mypy
        language: system
        types: [python]
        entry: poetry run mypy
        args: [--show-error-codes, --pretty]

      - id: checkov
        name: Scan using Checkov
        language: system
        types: [file]
        entry: checkov
        args: [-f]
