version: "3"

services:
  timescaledb:
    image: timescale/timescaledb:2.11.1-pg15
    volumes:
      - ./timescaledb/initdb:/docker-entrypoint-initdb.d
      - timescaledb-data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: password
      TIMESCALEDB_TELEMETRY: off

volumes:
  timescaledb-data: {}
